# Directories to scan for media
directories:
# Type of media we want to scan
fileTypes:
# configuration for media host (self)
mediaHost:
  scheme: http
  # port of the media host (self) instance
  port: 444
  # connection information for media manager
consul:
  scheme: http
  port: 8500
  address: 127.0.0.1
