# unique name for your host instance
name: my-media-host-1
# Directories to scan for media
directories:
# Type of media we want to scan
fileTypes:
# configuration for media host (self)
mediaHost:
  scheme: http
  # port of the media host (self) instance
  port: 444
  # Optional, if running in a container and consul is on another host need to provide address to reach the service within the container
  address: "127.0.0.1"
consul:
  scheme: http
  port: 8500
  address: 127.0.0.1
# config to connect to rabbitmq
rabbit:
  username: guest
  password: guest
  address: 10.0.0.124
  port: 5672
