openapi: 3.0.3
servers:
  - url: http://127.0.0.1:9797
info:
  title: Media host - OpenAPI 3.0
  description: |-
    Open API definition for media host APIs
  version: 1.0.0
tags:
  - name: Media
    description: Media on host
  - name: Health
    description: Health of the host
paths:
  /api/v1/media:
    get:
      tags:
        - Media
      summary: Get all media from host
      description: Gets all the available media items on the host
      operationId: getAllMedia
      parameters:
        - in: query
          name: mediaType
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
          required: false
          description: comma separated list of the type of media files to return
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MediaItem"
        "400":
          description: Invalid request
        "500":
          description: Failed to handle
  /api/v1/media/stream:
    get:
      tags:
        - Media
      summary: Stream selected file
      description: Must provide id for media item
      operationId: streamMedia

      parameters:
        - name: id
          in: query
          description: Id of the item to stream
          required: true
          schema:
            type: string
            format: uuid
        # - name: nodeId
        #   in: query
        #   description: Id of the node to play the media from
      responses:
        "200":
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                maxLength: 12345
        "400":
          description: Invalid status value
  /api/v1/media/download:
    post:
      tags:
        - Media
      summary: Download selected file(s)
      description: Returns a compressed archived of the file(s) requested for download from the provided media id(s).
      operationId: downloadMedia
      requestBody:
        description: the item(s) to download.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DownloadRequest"
      # parameters:
      # - name: strictDownload
      #   in: query
      #   description: Set strict download. If an error occurs when downloading any item the whole API will fail when strict is set to true. If set to false, the API will be treated successfully with a report of which item(s) failed to download.
      #   required: false
      #   default: false
      #   schema:
      #     type: boolean
      responses:
        "200":
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                maxLength: 12345
        "400":
          description: Invalid status value

  /api/v1/health:
    get:
      tags:
        - Health
      summary: Get health
      description: Determines if node is reachable
      operationId: getHealth
      responses:
        "200":
          description: successful operation
components:
  schemas:
    MediaItem:
      type: object
      properties:
        name:
          type: string
          example: some-file
        extension:
          type: string
          example: txt
        id:
          type: string
          format: uuid
        metadata:
          type: object
          additionalProperties: true
          example: { "title": "some-file" }
    DownloadRequest:
      type: array
      items:
        type: string
        format: uuid
